<?php echo $this->partial('partial/title', ['title' => $this->translate('Users')]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-0">
                    <?php echo $this->translate('Delete user'); ?>
                </h5>
            </div>
            <div class="col-md-6">
                <?php echo $this->partial('_actions'); ?>
            </div>
        </div>
    </div>

    <div class="card-body">
        <form method="post" name="delete" role="form" action="<?php echo $this->url('home/default', ['controller' => 'users', 'action' => 'delete', 'id' => $user->getId()]);?>" id="delete">
            <?php echo $this->partial('_view'); ?>

            <input type="submit" name="submit" class="btn btn-danger" id="submit" value="<?php echo $this->translate('Delete'); ?>">
        </form>
    </div>
</div>
