<?php echo $this->partial('partial/title', ['title' => $this->translate('Users')]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-0">
                    <?php echo $this->translate('Edit user'); ?>
                </h5>
            </div>
            <div class="col-md-6">
                <?php echo $this->partial('_actions'); ?>
            </div>
        </div>
    </div>
    <div class="card-body">
        <?php echo $this->partial('_form'); ?>
    </div>
</div>

