<?php echo $this->partial('partial/title', ['title' => $this->translate('Users')]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-0">
                    <?php echo $this->translate('View user'); ?>
                </h5>
            </div>
            <div class="col-md-6">
                <?php echo $this->partial('_actions'); ?>
            </div>
        </div>
    </div>

    <div class="card-body">
        <div class="form">
            <?php echo $this->partial('_view'); ?>
        </div>
    </div>
</div>
