<meta charset="utf-8">
<?php echo $this->headMeta()
    ->prependName('application-name', $this->settings('nome'))
    ->prependName('keywords', 'zetta code, responsive layout')
    ->prependName('description', $this->settings('nome'))
    ->prependName('author', 'Zetta Code')
    ->prependName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1')
    ->prependHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

<?php echo $this->headTitle($this->settings('name'))->setSeparator(' - ')->setAutoEscape(false) ?>

<!-- Le styles -->
<?php
if ($this->settings('css-custom') !== null) {
    $this->headLink()->prependStylesheet($this->basePath($this->settings('css-custom')));
}
echo $this->headLink()
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/beagle.css'))
    ->prependStylesheet($this->basePath('assets/animate.min.css'))
    ->prependStylesheet($this->basePath('assets/bootstrap-select/css/bootstrap-select.min.css'))
    ->prependStylesheet($this->basePath('assets/fontawesome/css/all.min.css'))
    ->prependStylesheet($this->basePath('assets/bootstrap/css/bootstrap.min.css'))
    ->setAutoEscape(false); ?>

<!-- Le inline styles -->
<?php echo $this->headStyle(); ?>

<!-- Touch icons -->
<link href="<?php echo $this->basePath('img/apple-touch-icon.png'); ?>" rel="apple-touch-icon">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo $this->basePath('assets/html5shiv.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/respond.min.js'); ?>"></script>
<![endif]-->

<!-- Start Scripts -->
<?php echo $this->headScript()->setAutoEscape(false); ?>
<!--  End Scripts-->

<!-- Favicon -->
<link href="<?php echo $this->basePath($this->settings('favicon')); ?>" rel="shortcut icon">
