<?php $begin = 2019; $year = date('Y'); ?>
<footer class="footer">
    <div class="container">
        <p class="text-muted">
            <a href="https://github.com/zetta-code/skeleton-application">
                <?php echo $this->settings('name') ?>
            </a>
            <?php echo $this->translate('was'); ?>
            <i class="fa fa-code text-success" title="<?php echo $this->translate('coded'); ?>"></i>
            <?php echo $this->translate('with'); ?>
            <i class="fa fa-heart text-danger" title="<?php echo $this->translate('love'); ?>"></i>
            <?php echo $this->translate('and'); ?>
            <i class="fa fa-coffee text-warning" title="<?php echo $this->translate('coffe'); ?>"></i>
            <?php echo $this->translate('by'); ?>
            <a href="https://github.com/zetta-code"> Zetta Code</a>.
        </p>
        <p class="text-muted">
            <i class="fa fa-copyright"></i><span class="sr-only">&copy</span>
            <?php echo $begin . ($year > $begin ? ' - ' . $year : ''); ?>
            Zetta Code - <?php echo $this->translate('All rights reserved') ?>.
        </p>
    </div>
</footer>