<?php echo $this->doctype(); ?>

<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->prependName('keywords', 'zetta code, responsive layout')
            ->prependName('description', 'ZF Skeleton App')
            ->prependName('author', 'Zetta Code')
            ->prependName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
            ->prependHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php echo $this->headTitle('ZF Skeleton App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Fav and touch icons -->
        <link href="<?php echo $this->basePath('img/favicon.png'); ?>" rel="icon">
        <link href="<?php echo $this->basePath('img/apple-touch-icon.png'); ?>" rel="apple-touch-icon">

        <!-- Le styles -->
        <?php echo $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('assets/animate.min.css'))
            ->prependStylesheet($this->basePath('assets/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/beagle.css'))
            ->prependStylesheet($this->basePath('assets/bootstrap/css/bootstrap.min.css')); ?>

        <!-- Le inline styles -->
        <?php echo $this->headStyle(); ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script type="text/javascript" src="<?php echo $this->basePath('js/html5shiv.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('js/respond.min.js'); ?>"></script>
        <![endif]-->

        <!-- Start Scripts -->
        <?php echo $this->headScript(); ?>
        <!--  End Scripts-->
    </head>
    <body>
        <!-- Start Navbar-->
        <?php echo $this->render('layout/default/navbar'); ?>
        <!-- End Navbar-->

        <!-- Start Content-->
        <div class="container main-content">
            <?php if ($this->placeholder('title')->getValue()): ?>
                <div class="page-head">
                    <h2 class="page-head-title"><?php echo $this->placeholder('title')->getValue(); ?></h2>
                    <?php if (!isset($breadcumb)): ?>
                        <?php echo $this->navigation('Zend\Navigation\Breadcrumbs')->breadcrumbs()->setPartial('partial/breadcrumbs') ;?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <!-- Start FlashMesseger-->
            <?php echo $this->zettaFlashMessenger(); ?>
            <!-- End FlashMesseger-->

            <?php echo $this->content; ?>
        </div>
        <!-- End Content-->

        <!-- Start Footer-->
        <?php echo $this->render('layout/default/footer'); ?>
        <!-- End Footer-->

        <!-- Javascripts -->
        <!-- Important javascript libs(put in all pages) -->
        <script type="text/javascript" src="<?php echo $this->basePath('assets/jquery/jquery-3.2.1.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/jquery/jquery.mask.min.js'); ?>"></script>
        <script type="text/javascript">var basePath = '<?php echo $this->basePath(); ?>';</script>

        <!-- Start Inline Scripts-->
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('js/default.js'))
            ->prependFile($this->basePath('assets/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/popper.min.js')); ?>
        <!-- End Inline Scripts-->
    </body>
</html>
