<?php echo $this->doctype(); ?>
<html lang="en-US">
    <head>
        <?php echo $this->partial('layout/default/_head'); ?>
    </head>
    <body>
        <!-- Start Navbar-->
        <?php echo $this->render('layout/default/navbar'); ?>
        <!-- End Navbar-->

        <!-- Start Content-->
        <div class="container main-content">
            <?php if ($this->placeholder('title')->getValue()): ?>
                <div class="page-head">
                    <h2 class="page-head-title"><?php echo $this->placeholder('title')->getValue(); ?></h2>
                    <?php if (!isset($breadcumb)): ?>
                        <?php echo $this->navigation('Zend\Navigation\Breadcrumbs')->breadcrumbs()->setPartial('partial/breadcrumbs') ;?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <!-- Start FlashMesseger-->
            <?php echo $this->zettaFlashMessenger(); ?>
            <!-- End FlashMesseger-->

            <?php echo $this->content; ?>
        </div>
        <!-- End Content-->

        <!-- Start Footer-->
        <?php echo $this->render('layout/default/footer'); ?>
        <!-- End Footer-->

        <?php echo $this->partial('layout/default/_scripts'); ?>
    </body>
</html>
